namespace ExpenseManager.Core.Currency;

/// <summary>Static ISO 4217 currency reference data used for the currency picker and amount formatting.</summary>
public static class CurrencyCatalog
{
    private static readonly List<CurrencyInfo> Raw =
    [
        new("USD", "US Dollar", "$"),
        new("EUR", "Euro", "€"),
        new("GBP", "British Pound", "£"),
        new("JPY", "Japanese Yen", "¥", 0),
        new("CNY", "Chinese Yuan", "¥"),
        new("INR", "Indian Rupee", "₹"),
        new("AUD", "Australian Dollar", "$"),
        new("CAD", "Canadian Dollar", "$"),
        new("CHF", "Swiss Franc", "CHF"),
        new("HKD", "Hong Kong Dollar", "$"),
        new("SGD", "Singapore Dollar", "$"),
        new("SEK", "Swedish Krona", "kr"),
        new("NOK", "Norwegian Krone", "kr"),
        new("DKK", "Danish Krone", "kr"),
        new("NZD", "New Zealand Dollar", "$"),
        new("KRW", "South Korean Won", "₩", 0),
        new("MXN", "Mexican Peso", "$"),
        new("BRL", "Brazilian Real", "R$"),
        new("ZAR", "South African Rand", "R"),
        new("RUB", "Russian Ruble", "₽"),
        new("TRY", "Turkish Lira", "₺"),
        new("AED", "UAE Dirham", "د.إ"),
        new("SAR", "Saudi Riyal", "﷼"),
        new("QAR", "Qatari Riyal", "﷼"),
        new("KWD", "Kuwaiti Dinar", "د.ك", 3),
        new("BHD", "Bahraini Dinar", ".د.ب", 3),
        new("OMR", "Omani Rial", "﷼", 3),
        new("JOD", "Jordanian Dinar", "د.ا", 3),
        new("ILS", "Israeli New Shekel", "₪"),
        new("EGP", "Egyptian Pound", "£"),
        new("PKR", "Pakistani Rupee", "₨"),
        new("BDT", "Bangladeshi Taka", "৳"),
        new("LKR", "Sri Lankan Rupee", "₨"),
        new("NPR", "Nepalese Rupee", "₨"),
        new("IDR", "Indonesian Rupiah", "Rp"),
        new("MYR", "Malaysian Ringgit", "RM"),
        new("THB", "Thai Baht", "฿"),
        new("PHP", "Philippine Peso", "₱"),
        new("VND", "Vietnamese Dong", "₫", 0),
        new("MMK", "Myanmar Kyat", "K"),
        new("KHR", "Cambodian Riel", "៛"),
        new("LAK", "Lao Kip", "₭"),
        new("BND", "Brunei Dollar", "$"),
        new("TWD", "New Taiwan Dollar", "$"),
        new("MOP", "Macanese Pataca", "P"),
        new("MNT", "Mongolian Tugrik", "₮"),
        new("KZT", "Kazakhstani Tenge", "₸"),
        new("UZS", "Uzbekistani Som", "so'm"),
        new("AZN", "Azerbaijani Manat", "₼"),
        new("GEL", "Georgian Lari", "₾"),
        new("AMD", "Armenian Dram", "֏"),
        new("PLN", "Polish Zloty", "zł"),
        new("CZK", "Czech Koruna", "Kč"),
        new("HUF", "Hungarian Forint", "Ft"),
        new("RON", "Romanian Leu", "lei"),
        new("BGN", "Bulgarian Lev", "лв"),
        new("HRK", "Croatian Kuna", "kn"),
        new("UAH", "Ukrainian Hryvnia", "₴"),
        new("ISK", "Icelandic Krona", "kr", 0),
        new("RSD", "Serbian Dinar", "дин."),
        new("ALL", "Albanian Lek", "L"),
        new("MKD", "Macedonian Denar", "ден"),
        new("BAM", "Bosnia-Herzegovina Mark", "KM"),
        new("MDL", "Moldovan Leu", "L"),
        new("BYN", "Belarusian Ruble", "Br"),
        new("EGP", "Egyptian Pound", "£"),
        new("MAD", "Moroccan Dirham", "د.م."),
        new("DZD", "Algerian Dinar", "د.ج"),
        new("TND", "Tunisian Dinar", "د.ت", 3),
        new("LYD", "Libyan Dinar", "ل.د", 3),
        new("IQD", "Iraqi Dinar", "ع.د", 3),
        new("IRR", "Iranian Rial", "﷼"),
        new("AFN", "Afghan Afghani", "؋"),
        new("LBP", "Lebanese Pound", "ل.ل"),
        new("SYP", "Syrian Pound", "£"),
        new("YER", "Yemeni Rial", "﷼"),
        new("NGN", "Nigerian Naira", "₦"),
        new("GHS", "Ghanaian Cedi", "₵"),
        new("KES", "Kenyan Shilling", "KSh"),
        new("TZS", "Tanzanian Shilling", "TSh"),
        new("UGX", "Ugandan Shilling", "USh", 0),
        new("RWF", "Rwandan Franc", "FRw", 0),
        new("ETB", "Ethiopian Birr", "Br"),
        new("XOF", "West African CFA Franc", "CFA", 0),
        new("XAF", "Central African CFA Franc", "FCFA", 0),
        new("XPF", "CFP Franc", "₣", 0),
        new("ZMW", "Zambian Kwacha", "ZK"),
        new("MWK", "Malawian Kwacha", "MK"),
        new("MZN", "Mozambican Metical", "MT"),
        new("BWP", "Botswana Pula", "P"),
        new("NAD", "Namibian Dollar", "$"),
        new("SZL", "Eswatini Lilangeni", "L"),
        new("LSL", "Lesotho Loti", "L"),
        new("MUR", "Mauritian Rupee", "₨"),
        new("SCR", "Seychellois Rupee", "₨"),
        new("MGA", "Malagasy Ariary", "Ar"),
        new("DJF", "Djiboutian Franc", "Fdj", 0),
        new("SOS", "Somali Shilling", "Sh"),
        new("SDG", "Sudanese Pound", "£"),
        new("GNF", "Guinean Franc", "FG", 0),
        new("XCD", "East Caribbean Dollar", "$"),
        new("BBD", "Barbadian Dollar", "$"),
        new("BSD", "Bahamian Dollar", "$"),
        new("BZD", "Belize Dollar", "$"),
        new("JMD", "Jamaican Dollar", "$"),
        new("TTD", "Trinidad & Tobago Dollar", "$"),
        new("HTG", "Haitian Gourde", "G"),
        new("DOP", "Dominican Peso", "RD$"),
        new("CUP", "Cuban Peso", "$"),
        new("GTQ", "Guatemalan Quetzal", "Q"),
        new("HNL", "Honduran Lempira", "L"),
        new("NIO", "Nicaraguan Cordoba", "C$"),
        new("CRC", "Costa Rican Colon", "₡"),
        new("PAB", "Panamanian Balboa", "B/."),
        new("COP", "Colombian Peso", "$"),
        new("VES", "Venezuelan Bolivar", "Bs."),
        new("GYD", "Guyanese Dollar", "$"),
        new("SRD", "Surinamese Dollar", "$"),
        new("PEN", "Peruvian Sol", "S/"),
        new("BOB", "Bolivian Boliviano", "Bs."),
        new("PYG", "Paraguayan Guarani", "₲", 0),
        new("UYU", "Uruguayan Peso", "$U"),
        new("CLP", "Chilean Peso", "$", 0),
        new("ARS", "Argentine Peso", "$"),
        new("FJD", "Fijian Dollar", "$"),
        new("PGK", "Papua New Guinean Kina", "K"),
        new("WST", "Samoan Tala", "T"),
        new("TOP", "Tongan Pa'anga", "T$"),
        new("VUV", "Vanuatu Vatu", "VT", 0),
        new("SBD", "Solomon Islands Dollar", "$"),
        new("SAR", "Saudi Riyal", "﷼"),
        new("KGS", "Kyrgyzstani Som", "с"),
        new("TJS", "Tajikistani Somoni", "SM"),
        new("TMT", "Turkmenistani Manat", "T"),
        new("BTN", "Bhutanese Ngultrum", "Nu."),
        new("MVR", "Maldivian Rufiyaa", ".ރ"),
        new("KPW", "North Korean Won", "₩"),
        new("BMD", "Bermudian Dollar", "$"),
        new("KYD", "Cayman Islands Dollar", "$"),
        new("AWG", "Aruban Florin", "ƒ"),
        new("ANG", "Netherlands Antillean Guilder", "ƒ"),
        new("XDR", "IMF Special Drawing Rights", "SDR"),
    ];

    public static readonly IReadOnlyList<CurrencyInfo> All = Raw
        .DistinctBy(c => c.Code)
        .OrderBy(c => c.Code, StringComparer.Ordinal)
        .ToList();

    public static CurrencyInfo? Find(string? code) =>
        string.IsNullOrWhiteSpace(code) ? null : All.FirstOrDefault(c => c.Code == code);

    public static readonly CurrencyInfo Default = Find("USD")!;
}
