// <auto-generated />
using System;
using ExpenseManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseManager.Data.Migrations
{
    [DbContext(typeof(ExpenseManagerDbContext))]
    [Migration("20260726075909_AddWallets")]
    partial class AddWallets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ExpenseManager.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Glyph")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#F97316",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Food & Dining",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#22C55E",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Groceries",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3B82F6",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Transport",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EC4899",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Shopping",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#EF4444",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Bills & Utilities",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Color = "#A855F7",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Entertainment",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Color = "#14B8A6",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Health",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6B7280",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Other",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Color = "#22C55E",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = "#3B82F6",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Freelance",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Color = "#F59E0B",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Investments",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Color = "#6B7280",
                            Glyph = "",
                            IsDefault = true,
                            Name = "Other Income",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ExpenseManager.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("Type");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseManager.Core.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#22C55E",
                            InitialBalance = 0m,
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Cash",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            InitialBalance = 0m,
                            IsArchived = false,
                            IsDefault = false,
                            Name = "Bank Account",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#A855F7",
                            InitialBalance = 0m,
                            IsArchived = false,
                            IsDefault = false,
                            Name = "Credit Card",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F97316",
                            InitialBalance = 0m,
                            IsArchived = false,
                            IsDefault = false,
                            Name = "Mobile Banking",
                            Type = 3
                        });
                });

            modelBuilder.Entity("ExpenseManager.Core.Entities.Transaction", b =>
                {
                    b.HasOne("ExpenseManager.Core.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseManager.Core.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ExpenseManager.Core.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseManager.Core.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
